name: Validate PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  # ====================================================================
  # Lint
  # ====================================================================
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run lint

  # ====================================================================
  # Tests
  # ====================================================================
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm test
      - run: npm pack --dry-run

  # ====================================================================
  # Build package
  # ====================================================================
  build:
    name: Test the build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm pack --dry-run
